### PR TITLE
#22 Add escape hatch for fatal exception on latest JDK versions.

### PR DESCRIPTION
**Pull request by arjantijms**
Note this fatal exception has been lurking in the code all along, but it
seems like in ~14 years nobody ever uses GMBAL on a code base where a
method had a generic type with two bounds.

Also updated .gitignore and pom.xml

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
cc @smillidge @dmatej @edbratt @russgold can you take a look? Thx!

**Review by m0mus — APPROVED** [review]
LGTM

**Review by smillidge — APPROVED** [review]

**Comment by smillidge** [comment]
@arjantijms can you fix the conflicts

**Comment by arjantijms** [comment]
@smillidge 
> @arjantijms can you fix the conflicts

It is done ;)

**Pull request merged**
