### PR TITLE
Integrate pfl 4.1.2,

### PR DESCRIPTION
**Pull request by lukasj**
update build plugins,
add missing export to api-only artifact

### CODE REVIEW

**Comment by lukasj** [comment]
@smillidge do you have enough power for this? Can you release new version (4.0.3) if this is merged eventually?

**Comment by smillidge** [comment]
I have the power

**Comment by lukasj** [comment]
@smillidge @arjantijms can this be merged and 4.0.3 with this change be released, please?

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
This should be merged in indeed quickly, ideally followed by #26 right away.

**Review by m0mus — APPROVED** [review]
LGTM

**Pull request merged**
